#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 1) Validate committer email

EMAIL=$(git config user.email)

case "$EMAIL" in
  *@alibaba-inc.com)
    echo "You are using a company email address.";
    echo "Please use your personal or GitHub email address instead.";
    echo "";
    echo "To configure your email for this repository, run:";
    echo "";
    echo "   git config user.email 'your.email@example.org'";
    echo "";
    exit 1;
    ;;
esac

# 2) Lint staged files

pnpm exec lint-staged
