name: "Code: CI"

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^8.8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps
        run: pnpm install --ignore-scripts

      - uses: nrwl/nx-set-shas@v4
        # https://nx.dev/recipes/ci/monorepo-ci-github-actions

      - name: Run linters and formatters
        run: pnpm run ci

      - name: Run TypeScript type checking
        run: pnpm nx affected --target=lint:typing --nx-bail=true

      - name: Run tests
        run: pnpm nx affected --target=test --nx-bail=true
